# Generated by Django 5.1.4 on 2024-12-24 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_reviewrating_delete_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviewrating",
            name="rating",
            field=models.FloatField(blank=True),
        ),
    ]
