# Generated by Django 5.1.4 on 2024-12-24 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_alter_reviewrating_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviewrating",
            name="rating",
            field=models.FloatField(),
        ),
    ]
