# Generated by Django 5.1.4 on 2024-12-27 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SmallBanners",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "smallimages",
                    models.ImageField(null=True, upload_to="photos/smallbanners"),
                ),
            ],
            options={
                "verbose_name": "SmallBanner",
                "verbose_name_plural": "SmallBanners",
            },
        ),
        migrations.AlterModelOptions(
            name="banners",
            options={"verbose_name": "Banner", "verbose_name_plural": "Banners"},
        ),
    ]
