# Generated by Django 5.1.4 on 2024-12-14 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="email",
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="phone_number",
            field=models.IntegerField(max_length=50),
        ),
    ]
