# Generated by Django 5.1.4 on 2024-12-14 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_account_email_alter_account_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="phone_number",
            field=models.CharField(max_length=50),
        ),
    ]
