# Generated by Django 5.1.4 on 2024-12-22 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0003_cartitem_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cartitem",
            old_name="variation",
            new_name="variations",
        ),
    ]
